name: AllAPILoader
main: BeckenPlayZMCPE\AllAPILoader\Main
version: null
api: 3.0.0-ALPHA12
author: BeckenPlayZMCPE
description: 'Makes the server load every plugin regardless of the API version'
load: STARTUP
softdepend:
    - DevTools
    - FolderPluginLoader
